print_str("2 ");
foreach(i, 3, 100);
var flag = 1;
foreach(j, 2, i);
(i % j == 0).if_begin();
flag = 0;
if_end();
endfor(j, 2, i);
flag.if_begin();
i.output_as_integer();
output(' ');
flag.if_end();
endfor(i, 3, 100);
output('\n');